xcodeproj 'GithubStats/GithubStats.xcodeproj'
platform :ios, '6.1'
pod 'SVProgressHUD', '~> 0.9'
pod 'MagicalRecord', '~> 2.1'
pod 'TapkuLibrary', :git => 'git@github.com:nguyenhuy/tapkulibrary.git'
pod 'UAGithubEngine', :git => 'git@github.com:nguyenhuy/UAGithubEngine.git'
pod 'FDStatusBarNotifierView', '~> 0.1.0'
